// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// GameAPI is an autogenerated mock type for the GameAPI type
type GameAPI struct {
	mock.Mock
}

type GameAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *GameAPI) EXPECT() *GameAPI_Expecter {
	return &GameAPI_Expecter{mock: &_m.Mock}
}

// Choice provides a mock function with given fields: _a0, _a1
func (_m *GameAPI) Choice(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// GameAPI_Choice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Choice'
type GameAPI_Choice_Call struct {
	*mock.Call
}

// Choice is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *GameAPI_Expecter) Choice(_a0 interface{}, _a1 interface{}) *GameAPI_Choice_Call {
	return &GameAPI_Choice_Call{Call: _e.mock.On("Choice", _a0, _a1)}
}

func (_c *GameAPI_Choice_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *GameAPI_Choice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *GameAPI_Choice_Call) Return() *GameAPI_Choice_Call {
	_c.Call.Return()
	return _c
}

// Choices provides a mock function with given fields: _a0, _a1
func (_m *GameAPI) Choices(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// GameAPI_Choices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Choices'
type GameAPI_Choices_Call struct {
	*mock.Call
}

// Choices is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *GameAPI_Expecter) Choices(_a0 interface{}, _a1 interface{}) *GameAPI_Choices_Call {
	return &GameAPI_Choices_Call{Call: _e.mock.On("Choices", _a0, _a1)}
}

func (_c *GameAPI_Choices_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *GameAPI_Choices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *GameAPI_Choices_Call) Return() *GameAPI_Choices_Call {
	_c.Call.Return()
	return _c
}

// Play provides a mock function with given fields: _a0, _a1
func (_m *GameAPI) Play(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// GameAPI_Play_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Play'
type GameAPI_Play_Call struct {
	*mock.Call
}

// Play is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *GameAPI_Expecter) Play(_a0 interface{}, _a1 interface{}) *GameAPI_Play_Call {
	return &GameAPI_Play_Call{Call: _e.mock.On("Play", _a0, _a1)}
}

func (_c *GameAPI_Play_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *GameAPI_Play_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *GameAPI_Play_Call) Return() *GameAPI_Play_Call {
	_c.Call.Return()
	return _c
}

type mockConstructorTestingTNewGameAPI interface {
	mock.TestingT
	Cleanup(func())
}

// NewGameAPI creates a new instance of GameAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGameAPI(t mockConstructorTestingTNewGameAPI) *GameAPI {
	mock := &GameAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
